/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "buttonAdvance": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonAdvance" },
    "buttonAspect": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonAspect" },
    "buttonChannelDown": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonChannelDown" },
    "buttonChannelUp": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonChannelUp" },
    "buttonClear": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonClear" },
    "buttonDisplay": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonDisplay" },
    "buttonDown": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonDown" },
    "buttonEnter": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonEnter" },
    "buttonForward": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonForward" },
    "buttonGuide": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonGuide" },
    "buttonInfo": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonInfo" },
    "buttonLeft": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonLeft" },
    "buttonLiveTv": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonLiveTv" },
    "buttonNum0": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonNum0" },
    "buttonNum1": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonNum1" },
    "buttonNum2": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonNum2" },
    "buttonNum3": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonNum3" },
    "buttonNum4": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonNum4" },
    "buttonNum5": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonNum5" },
    "buttonNum6": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonNum6" },
    "buttonNum7": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonNum7" },
    "buttonNum8": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonNum8" },
    "buttonNum9": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonNum9" },
    "buttonPause": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonPause" },
    "buttonPlay": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonPlay" },
    "buttonRecord": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonRecord" },
    "buttonReplay": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonReplay" },
    "buttonReverse": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonReverse" },
    "buttonRight": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonRight" },
    "buttonSelect": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonSelect" },
    "buttonSlow": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonSlow" },
    "buttonThumbsDown": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonThumbsDown" },
    "buttonThumbsUp": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonThumbsUp" },
    "buttonTivo": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonTivo" },
    "buttonUp": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonClickHandler", "rightImageWidth": 5, "text": "ButtonUp" },
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "titleText": { "text": "title", "view": "DC.Text" }
};




